name: restaurant
recipe: laravel
config:
  php: '7.3'
  webroot: public
  via: nginx
  database: postgres
  xdebug: true
services:
  database:
    portforward: 5433

  node:
    type: node
    build:
      - npm install


tooling:
  npm:
    service: node

  phpunit:
    service: appserver
    description: "Run PHP Unit tests: lando phpunit"
    cmd: /app/vendor/bin/phpunit